### ISSUE TITLE
Server Stops working after first attend to print to TSP650 on Network.

### ISSUE THREAD

**Issue by ray-moncada** [Tecdiary/ppp#2]
I installed server and added the printer. 
My server is running php 7.1.8

Printer information 
MANUFACTURER: | Star
COMMAND SET: | STAR
MODEL: | TSP654 (STR_T-001)
CLASS: | PRINTER

The printer will print part of the receipt and then the printer stops.

This is the output on the console
> php server.php
> Starting server...
> Server started
> Connected
> Received request {"type":"print-receipt","data":{"printer":{"id":"0184fecc0d8c8858f6f174155d4c3a2b","title":"TSP650","type":"network","profile":"simple","char_per_line":"80","path":"","ip_address":"10.0.110.208","port":"9100"},"logo":"logo1.png","text":{"store_name":"Test Biller\n","header":"Test Biller\nBiller adddress\nCity Country\nTel: 01234567
8\n\nGST Reg: 123456789\nVAT Reg: 987654321\n\n","info":"Date: 08/05/2017 10:38\nSale No/Ref: 15\nSales Associate: Owner Owner\n\nCustomer: Walk-in Customer\n","items":"#1 FFR07 - Yellow Watermelon           *Z\n   2.500 kg x 2.50                   6.25\n#2 FFR06 - Watermelon                  *Z\n   2.500 kg x 2.50                   6.25\n","totals":
"Total:                              12.50\nGrand Total:                        12.50\nPaid Amount:                        12.50\nDue Amount:                          0.00\n","payments":"Paid by:                             Cash\nAmount:                             12.50\nChange:                              0.00\n","footer":" Thank you for shopping
with us. \nPlease come again\n\n"}}}
> Printing
> Printied

**Comment by MianSaleem** [comment]
Log has no information about issue, it shows `printed`. Did you try your printer with different profile?

**Comment by ray-moncada** [comment]
What other profile can you recommend that is similar to TSP650?

**Comment by ray-moncada** [comment]
Hi,

I was able to get to print. I lower the number of characters per line to 50 and that solved the problem.

I have another problem I am not able to print from the POS, below is how the POS is configured. 

I have the POS system hosted on an AWS instance. 

I have the TSP650 Printer on a local network intranet. 

I set up the PHP POS Print Server on a local machine in the local network. (I am able to print without a problem) 

I added the printer on the AWS instance and on the local POS Print Server.

When I checkout in the POS I get the following error”

“Unable to connect to socket, please make sure that server is up and running fine.”

I am new to this configuration, what am I missing?

Thank you in advance,


Ray Moncada
Director of Information Technology

**Comment by MianSaleem** [comment]
Please go to pos settings and select **PHP POS Print server** and Yes for **Use local printers** Then you can view any receipt and if get same error means you ppp server is not running, run and then it will be fine. Thank you

**Comment by ray-moncada** [comment]
Thank you for the information. I am not sure why the server stops working on the local machine. Can you provide a list of PHP extensions, I should be running on the local machine?

**Comment by MianSaleem** [comment]
As I guess you are using windows installer and all required extensions are already in exe file :( 

You can try to download/clone/fork this repo to try on same machine to check if it work or having same issue?

**Comment by ray-moncada** [comment]
I installed from the repo. and I get the same error on the same machine. I also installed on a mac. also installed the imagegick and guzzle suggested by mike42 dependency. The printer only prints only part of the receipt. The PHP POS Server stays running but the receipt does not print.

**Comment by MianSaleem** [comment]
You don't have to worry about dependencies as composer will handle when you install/update. I am clueless as log says printed but printer prints only part, you have tested on different machine with same result. Something with printer model as it's not listed mean no one else test this model too that left you with the option to print from web browser :(

**Comment by ray-moncada** [comment]
I contacted Star Micronics for help with the TSP650II printer. They suggested to switch the network card. I placed an order for a new network card. Will keep you posted.

**Comment by ray-moncada** [comment]
the printers needs a network card that support webPRNT and the json response needs to be text only.

**Comment by kdrmlhcn** [comment]
@ray-moncada did you solve this problem?
